# Generated by Django 3.0.4 on 2020-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0003_auto_20200410_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='projectslist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectslist',
            name='technology',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectslist',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projectslist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
