# Generated by Django 3.0.4 on 2020-04-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0004_auto_20200410_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectslist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectslist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
