# Generated by Django 3.0.4 on 2020-04-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0008_moreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='Highschoolcgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='Highschoolname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
