# Generated by Django 3.0.4 on 2020-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0012_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
