# Generated by Django 3.0.4 on 2020-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0013_auto_20200411_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
