# Generated by Django 3.0.4 on 2020-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portf1', '0014_auto_20200411_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreinfo',
            name='college_end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='college_start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='high_school_end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='high_school_start_year',
            field=models.IntegerField(null=True),
        ),
    ]
